target . delete ( "__TARGET4__" ) 
say_title ( gameforge . new_quest_lv28 . _019_say_title ) 
say ( gameforge . new_quest_lv28 . _051_say ) 
local b = select ( gameforge . new_quest_lv28 . _055_1_select , gameforge . new_quest_lv28 . _055_2_select ) 
if b == 1 then 
say_title ( gameforge . new_quest_lv28 . _019_say_title ) 
say ( gameforge . new_quest_lv28 . _056_say ) 
q . done ( ) 
give_reward ( "new_quest_lv28_gold" ) 
set_state ( "__COMPLETE__" ) 
end 
if b == 2 then 
say_title ( gameforge . new_quest_lv28 . _019_say_title ) 
say ( gameforge . new_quest_lv28 . _057_say ) 
set_state ( "__COMPLETE__" ) 
give_reward ( "new_quest_lv28_exp" ) 
q . done ( ) 
end 
