target . delete ( "__TARGET__" ) 
if pc . count_item ( 30161 ) < 3 then 
say_title ( gameforge . subquest_20 . _300_sayTitle ) 
say ( gameforge . subquest_20 . _310_say ) 
local z = select ( gameforge . subquest_20 . _320_select , gameforge . subquest_20 . _330_select ) 
if 2 == z then 
say ( gameforge . subquest_20 . _340_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say ( gameforge . subquest_20 . _350_say ) 
else 
say_title ( gameforge . subquest_20 . _300_sayTitle ) 
pc . remove_item ( 30161 , 3 ) 
say ( gameforge . subquest_20 . _360_say ) 
set_state ( "__COMPLETE__" ) 
give_reward ( "subquest_20" ) 
clear_letter ( ) 
end 
