target . delete ( "__TARGET__" ) 
if pc . getqf ( "ironore_done" ) ~= 1 then 
say_title ( gameforge . blacksmith . _20_sayTitle ) 
say ( gameforge . subquest_06 . _440_say ) 
return 
end 
if pc . getqf ( "leather_done" ) ~= 1 then 
say_title ( gameforge . blacksmith . _20_sayTitle ) 
say ( gameforge . subquest_06 . _450_say ) 
return 
end 
if pc . getqf ( "coal_done" ) ~= 1 then 
say_title ( gameforge . blacksmith . _20_sayTitle ) 
say ( gameforge . subquest_06 . _460_say ) 
return 
end 
