target . delete ( "__TARGET__" ) 
if pc . count_item ( 60 ) >= 20 then 
say_title ( gameforge . main_quest_lv32 . _120_sayTitle ) 
say ( gameforge . main_quest_lv32 . _210_say ) 
wait ( ) 
say_title ( gameforge . main_quest_lv32 . _120_sayTitle ) 
say ( gameforge . main_quest_lv32 . _220_say ) 
pc . remove_item ( 60 , 20 ) 
set_state ( "gotodoc" ) 
else 
say_title ( gameforge . main_quest_lv32 . _230_sayTitle ) 
say ( gameforge . main_quest_lv32 . _240_say ) 
end 
