target . delete ( "__TARGET__" ) 
say_title ( gameforge . main_quest_lv32 . _120_sayTitle ) 
say ( gameforge . subquest_32 . _30_say ) 
wait ( ) 
say_title ( gameforge . main_quest_lv32 . _120_sayTitle ) 
say ( gameforge . subquest_32 . _40_say ) 
wait ( ) 
say_title ( gameforge . main_quest_lv32 . _120_sayTitle ) 
say ( gameforge . subquest_32 . _50_say ) 
local s = select ( gameforge . subquest_01 . _50_select , gameforge . subquest_01 . _60_select ) 
if 2 == s then 
say ( gameforge . subquest_32 . _60_say ) 
local a = select ( gameforge . subquest_12 . _select_yes , gameforge . subquest_12 . _select_no ) 
if 2 == a then 
say_title ( gameforge . main_quest_lv32 . _120_sayTitle ) 
say ( gameforge . subquest_32 . _70_say ) 
return 
end 
say_title ( gameforge . main_quest_lv32 . _120_sayTitle ) 
say ( gameforge . subquest_32 . _80_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . main_quest_lv32 . _120_sayTitle ) 
say ( gameforge . subquest_32 . _90_say ) 
set_state ( "gogogo" ) 
