if pc . count_item ( 30131 ) >= 1 then 
target . delete ( "__TARGET__" ) 
say_title ( gameforge . subquest_04 . _150_sayTitle ) 
say ( gameforge . subquest_04 . _160_say ) 
wait ( ) 
say_title ( gameforge . subquest_04 . _150_sayTitle ) 
say ( gameforge . subquest_04 . _170_say ) 
pc . remove_item ( "30131" , 1 ) 
set_state ( "return_to" ) 
else 
say_title ( gameforge . subquest_04 . _150_sayTitle ) 
say ( gameforge . subquest_04 . _180_say ) 
local s = select ( gameforge . subquest_04 . _190_select , gameforge . subquest_04 . _200_select ) 
if 2 == s then 
say ( gameforge . subquest_04 . _210_say ) 
local a = select ( gameforge . subquest_12 . _select_yes , gameforge . subquest_12 . _select_no ) 
if 2 == a then 
say_title ( gameforge . mining . _10_sayTitle ) 
say ( gameforge . subquest_04 . _220_say ) 
return 
end 
say_title ( gameforge . mining . _10_sayTitle ) 
say ( gameforge . subquest_04 . _230_say ) 
clear_letter ( ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . mining . _10_sayTitle ) 
say ( gameforge . subquest_04 . _240_say ) 
set_state ( "information" ) 
end 
