target . delete ( "__TARGET__" ) 
say_title ( gameforge . new_quest_lv29 . _020_say_title ) 
say ( gameforge . new_quest_lv29 . _021_say ) 
say ( gameforge . new_quest_lv29 . _022_say ) 
local goto_npc = 20005 
local accept = select ( gameforge . new_quest_lv29 . _023_1_select , gameforge . new_quest_lv29 . _023_2_select ) 
if accept == 1 then 
local v = find_npc_by_vnum ( 20014 ) 
if 0 ~= v then 
target . vid ( "__TARGET2__" , v , gameforge . new_quest_lv29 . _030_target ) 
end 
set_state ( "find_taurean" ) 
else 
say ( gameforge . new_quest_lv29 . _024_say ) 
say ( gameforge . subquest_06 . _60_say ) 
local abortquest = select ( gameforge . subquest_06 . _70_select , gameforge . subquest_06 . _80_select ) 
if abortquest == 1 then 
pc . setqf ( "hayIndex" , 0 ) 
pc . setqf ( "hayFromHarang" , 0 ) 
pc . setqf ( "hayFromTaurean" , 0 ) 
pc . setqf ( "hayFromStablemaster" , 0 ) 
pc . setqf ( "yonahspatience" , 0 ) 
pc . setqf ( "yonahHasHay" , 0 ) 
pc . setqf ( "dropProb" , 0 ) 
set_state ( "__GIVEUP__" ) 
else 
local v = find_npc_by_vnum ( goto_npc ) 
if 0 ~= v then 
target . vid ( "__TARGET__" , v , gameforge . new_quest_lv29 . _010_target ) 
end 
return 
end 
end 
