target . delete ( "__TARGET__" ) 
say_title ( gameforge . subquest_39 . _160_sayTitle ) 
say ( gameforge . subquest_39 . _170_say ) 
wait ( ) 
say_title ( gameforge . collect_quest_lv30 . _340_sayTitle ) 
say ( gameforge . subquest_39 . _180_say ) 
wait ( ) 
say_title ( gameforge . collect_quest_lv30 . _340_sayTitle ) 
say ( gameforge . subquest_39 . _190_say ) 
local b = select ( gameforge . subquest_39 . _200_select , gameforge . subquest_39 . _210_select ) 
if 2 == b then 
say ( gameforge . subquest_39 . _220_say ) 
local a = select ( gameforge . subquest_39 . _230_select , gameforge . locale . guild . no ) 
if 2 == a then 
say_title ( gameforge . collect_quest_lv30 . _340_sayTitle ) 
say ( gameforge . subquest_39 . _240_say ) 
return 
end 
say_title ( gameforge . collect_quest_lv30 . _340_sayTitle ) 
say ( gameforge . subquest_39 . _250_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . collect_quest_lv30 . _340_sayTitle ) 
say ( gameforge . subquest_39 . _260_say ) 
set_state ( "hunt_monkey_boss" ) 
