enum ESkillFlags
{
	SKILL_FLAG_ATTACK = (1 << 0),
	SKILL_FLAG_USE_MELEE_DAMAGE = (1 << 1),
	SKILL_FLAG_COMPUTE_ATTGRADE = (1 << 2),
	SKILL_FLAG_SELFONLY = (1 << 3),
	SKILL_FLAG_USE_MAGIC_DAMAGE = (1 << 4),
	SKILL_FLAG_USE_HP_AS_COST = (1 << 5),
	SKILL_FLAG_COMPUTE_MAGIC_DAMAGE = (1 << 6),
	SKILL_FLAG_SPLASH = (1 << 7),
	SKILL_FLAG_GIVE_PENALTY = (1 << 8),
	SKILL_FLAG_USE_ARROW_DAMAGE = (1 << 9),
	SKILL_FLAG_PENETRATE = (1 << 10),
	SKILL_FLAG_IGNORE_TARGET_RATING = (1 << 11),
	SKILL_FLAG_SLOW = (1 << 12),
	SKILL_FLAG_STUN = (1 << 13),
	SKILL_FLAG_HP_ABSORB = (1 << 14),
	SKILL_FLAG_SP_ABSORB = (1 << 15),
	SKILL_FLAG_FIRE_CONT = (1 << 16),
	SKILL_FLAG_REMOVE_BAD_AFFECT = (1 << 17),
	SKILL_FLAG_REMOVE_GOOD_AFFECT = (1 << 18),
	SKILL_FLAG_CRUSH = (1 << 19),
	SKILL_FLAG_POISON = (1 << 20),
	SKILL_FLAG_TOGGLE = (1 << 21),
	SKILL_FLAG_DISABLE_BY_POINT_UP = (1 << 22),
	SKILL_FLAG_CRUSH_LONG = (1 << 23),
	//SKILL_FLAG_WIND = (1 << 24),
	//SKILL_FLAG_ELEC = (1 << 25),
	//SKILL_FLAG_FIRE = (1 << 26),
	SKILL_FLAG_CRUSH_MOB = (1 << 24),
	SKILL_FLAG_STUN_MOB = (1 << 25),
	SKILL_FLAG_THIRD_POINT_SELFONLY = (1 << 26),
#ifdef ENABLE_WOLFMAN_CHARACTER
	SKILL_FLAG_BLEEDING = (1 << 27),
#endif
#ifdef ENABLE_SKILL_FLAG_PARTY
	SKILL_FLAG_PARTY = (1 << 28),
#endif
};

enum
{
	SKILL_TYPE_NONE,
	SKILL_TYPE_ACTIVE,
	SKILL_TYPE_SUPPORT,
	SKILL_TYPE_GUILD,
	SKILL_TYPE_UNUSED01,
	SKILL_TYPE_HORSE,
	SKILL_TYPE_MAX_NUM,
};

enum ESkillIndexes
{
	SKILL_RESERVED = 0,

	SKILL_THREE_WAY_CUT = 1,
	SKILL_SWORD_SPIN,
	SKILL_BERSERK,
	SKILL_SWORD_AURA,
	SKILL_CHARGE,

	SKILL_SPIRIT_STRIKE = 16,
	SKILL_BASH,
	SKILL_STUMP,
	SKILL_STRONG_BODY,
	SKILL_SWORD_STRIKE,

	SKILL_AMBUSH = 31,
	SKILL_FAST_ATTACK,
	SKILL_ROLLING_DAGGER,
	SKILL_STEALTH,
	SKILL_POISON_CLOUD,

	SKILL_ARCHER_START = 46,
	SKILL_REPETITIVE_SHOT = SKILL_ARCHER_START,
	SKILL_SPARK,
	SKILL_FIRE_ARROW,
	SKILL_FEATHER_WALK,
	SKILL_POISON_ARROW,
	SKILL_ARROW_SHOWER,
	SKILL_ARCHER_END = SKILL_POISON_ARROW,


	SKILL_FINGER_STRIKE = 61,
	SKILL_DRAGON_SWIRL,
	SKILL_ENCHANTED_BLADE,
	SKILL_TERROR,
	SKILL_ENCHANTED_ARMOR,
	SKILL_DISPEL,

	SKILL_DARK_STRIKE = 76,
	SKILL_FLAME_STRIKE,
	SKILL_FLAME_SPIRIT,
	SKILL_MANASHIELD,
	SKILL_SPIRIT_ORB,
	SKILL_DARK_ORB,

	SKILL_FLYING_TALISMAN = 91,
	SKILL_SHOOTING_DRAGON,
	SKILL_DRAGON_ROAR,
	SKILL_BLESSING,
	SKILL_REFLECT,
	SKILL_DRAGON_HELP,

	SKILL_LIGHTNING_THROW = 106,
	SKILL_SUMMON_LIGHTNING,
	SKILL_LIGHTNING_CLAW,
	SKILL_CURE,
	SKILL_SWIFTNESS,
	SKILL_ATTACK_UP,

	SKILL_PLAYER_MAX,

	SKILL_7_A_ANTI_TANHWAN = 112,
	SKILL_7_B_ANTI_AMSEOP,
	SKILL_7_C_ANTI_SWAERYUNG,
	SKILL_7_D_ANTI_YONGBI,

	SKILL_8_A_ANTI_GIGONGCHAM,
	SKILL_8_B_ANTI_YEONSA,
	SKILL_8_C_ANTI_MAHWAN,
	SKILL_8_D_ANTI_BYEURAK,

	SKILL_LEADERSHIP = 121,
	SKILL_COMBO = 122,
	SKILL_CREATE = 123,
	SKILL_MINING = 124,

	SKILL_LANGUAGE1 = 126,
	SKILL_LANGUAGE2 = 127,
	SKILL_LANGUAGE3 = 128,
	SKILL_POLYMORPH = 129,

	SKILL_HORSE = 130,
	SKILL_HORSE_SUMMON = 131,
	SKILL_SPRINT = 132,

	SKILL_HORSE_WILDATTACK = 137,
	SKILL_HORSE_CHARGE = 138,
	SKILL_HORSE_ESCAPE = 139,
	SKILL_HORSE_WILDATTACK_RANGE = 140,

	SKILL_ADD_HP = 141,
	SKILL_RESIST_PENETRATE = 142,

	SKILL_PASSIVE_MAX,

	GUILD_SKILL_START = 151,
	GUILD_SKILL_EYE = 151,
	GUILD_SKILL_BLOOD = 152,
	GUILD_SKILL_BLESS = 153,
	GUILD_SKILL_SEONGHWI = 154,
	GUILD_SKILL_ACCEL = 155,
	GUILD_SKILL_BUNNO = 156,
	GUILD_SKILL_JUMUN = 157,
	GUILD_SKILL_TELEPORT = 158,
	GUILD_SKILL_DOOR = 159,
	GUILD_SKILL_END = 162,

	GUILD_SKILL_COUNT = GUILD_SKILL_END - GUILD_SKILL_START + 1,

};
// Files shared by Metin2hub.com
