say_title ( gameforge . new_quest_lv52 . _054_say_title ) 
say ( gameforge . new_quest_lv52 . _042_say ) 
local doquest = select ( gameforge . new_quest_lv52 . _055_select , gameforge . subquest_12 . _50_select , gameforge . new_quest_lv75 . _290_2_select ) 
if doquest == 1 then 
say_title ( gameforge . new_quest_lv52 . _054_say_title ) 
say ( gameforge . new_quest_lv52 . _056_say ) 
elseif doquest == 3 then 
say ( gameforge . subquest_06 . _60_say ) 
local abortquest = select ( gameforge . subquest_06 . _70_select , gameforge . subquest_06 . _80_select ) 
if abortquest == 1 then 
pc . setqf ( "ghostsleft" , 0 ) 
target . delete ( "__TARGET__" ) 
set_state ( "__GIVEUP__" ) 
else 
say_title ( gameforge . new_quest_lv52 . _054_say_title ) 
say ( gameforge . subquest_11 . _80_say ) 
end 
return 
else 
say_title ( gameforge . new_quest_lv52 . _054_say_title ) 
say ( gameforge . new_quest_lv52 . _85_say ) 
end 
