say_title ( gameforge . subquest_34 . _20_sayTitle ) 
say ( gameforge . subquest_34 . _110_say ) 
local s = select ( gameforge . subquest_34 . _120_select , gameforge . subquest_31 . _180_select ) 
if 2 == s then 
say ( gameforge . subquest_34 . _130_say ) 
local a = select ( gameforge . subquest_12 . _select_yes , gameforge . subquest_12 . _select_no ) 
if 2 == a then 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_34 . _140_say ) 
return 
end 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_34 . _150_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_34 . _160_say ) 
