target . delete ( "__TARGET__" ) 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_48 . _20_say ) 
wait ( ) 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_48 . _30_say ) 
wait ( ) 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_48 . _40_say ) 
local r = select ( gameforge . find_brother_article . _90_select , gameforge . find_brother_article . _100_select ) 
if 2 == r then 
say ( gameforge . subquest_48 . _50_say ) 
local a = select ( gameforge . subquest_12 . _select_yes , gameforge . subquest_12 . _select_no ) 
if 2 == a then 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_48 . _60_say ) 
return 
end 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_48 . _70_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_48 . _80_say ) 
set_state ( "go_to_otherland" ) 
