target . delete ( "__TARGET__" ) 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_16 . _30_say ) 
wait ( ) 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_16 . _40_say ) 
local s = select ( gameforge . subquest_05 . _70_select , gameforge . subquest_08 . _170_select ) 
if 2 == s then 
say ( gameforge . subquest_11 . _60_say ) 
local a = select ( gameforge . subquest_12 . _select_yes , gameforge . subquest_12 . _select_no ) 
if 2 == a then 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_16 . _50_say ) 
return 
end 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_16 . _60_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . main_quest_lv10 . _30_sayTitle ) 
say ( gameforge . subquest_16 . _70_say ) 
set_state ( "ask_to_youhwan" ) 
