if collect_data . is_wait ( ) then 
say_title ( gameforge . collect_quest_lv85 . _185_say ) 
say ( gameforge . collect_quest_lv85 . _190_say ) 
return 
end 
if pc . count_item ( 30166 ) < 1 then 
say_title ( gameforge . collect_quest_lv85 . _149_say ) 
say ( gameforge . collect_quest_lv85 . no_item ) 
return 
end 
say_title ( gameforge . collect_quest_lv85 . _149_say ) 
say ( gameforge . collect_quest_lv85 . _150_say ) 
pc . remove_item ( 30167 , 1 ) 
wait ( ) 
local if_fail_show_wait_info = not collect_data . is_no_time_on_fail ( ) 
if collect_data . take_chance ( 60 ) then 
if pc . getqf ( "collect_count" ) < 39 then 
local index = pc . getqf ( "collect_count" ) + 1 
pc . setqf ( "collect_count" , index ) 
say_title ( gameforge . collect_quest_lv85 . _159_say ) 
say ( gameforge . collect_quest_lv85 . _160_say ) 
say ( gameforge . collect_quest_lv85 . _165_1_say .. " " .. 40 - pc . getqf ( "collect_count" ) .. gameforge . collect_quest_lv85 . _165_2_say ) 
say ( gameforge . collect_quest_lv85 . _170_say ) 
return 
end 
say_title ( gameforge . collect_quest_lv85 . _174_say ) 
say ( gameforge . collect_quest_lv85 . _175_say ) 
pc . setqf ( "collect_count" , 0 ) 
collect_data . reset_time ( ) 
set_state ( "key_item" ) 
return 
else 
say_title ( gameforge . collect_quest_lv85 . _179_say ) 
say ( gameforge . collect_quest_lv85 . _180_say ) 
say ( ) 
if if_fail_show_wait_info then 
say ( gameforge . collect_quest_lv85 . fail_wait_info ) 
end 
return 
end 
