if collect_data . is_wait ( ) then 
npc_name ( ) 
say ( gameforge . collect_quest_lv90 . _190_say ) 
say ( "" ) 
return 
end 
if pc . count_item ( 30168 ) < 1 then 
npc_name ( ) 
say ( gameforge . collect_quest_lv90 . _185_say ) 
return 
end 
npc_name ( ) 
say ( gameforge . collect_quest_lv90 . _150_say ) 
say ( "" ) 
pc . remove_item ( 30168 , 1 ) 
wait ( ) 
local if_fail_show_wait_info = not collect_data . is_no_time_on_fail ( ) 
if collect_data . take_chance ( 60 ) then 
if pc . getqf ( "collect_count" ) < 49 then 
local index = pc . getqf ( "collect_count" ) + 1 
pc . setqf ( "collect_count" , index ) 
npc_name ( ) 
say ( gameforge . collect_quest_lv90 . _160_say ) 
say ( string . format ( gameforge . collect_quest_lv90 . _165_say , 50 - pc . getqf ( "collect_count" ) ) ) 
say ( gameforge . collect_quest_lv90 . _170_say ) 
say ( "" ) 
return 
end 
npc_name ( ) 
say ( gameforge . collect_quest_lv90 . _175_say ) 
say ( "" ) 
pc . setqf ( "collect_count" , 0 ) 
collect_data . reset_time ( ) 
set_state ( "key_item" ) 
return 
else 
npc_name ( ) 
say ( gameforge . collect_quest_lv90 . _180_say ) 
say ( "" ) 
if if_fail_show_wait_info then 
say ( gameforge . collect_quest_lv90 . fail_wait_info ) 
end 
return 
end 
