if collect_data . is_wait ( ) then 
say_title ( gameforge . collect_quest_lv60 . _50_sayTitle ) 
say ( gameforge . collect_quest_lv60 . _210_say ) 
return 
end 
if pc . count_item ( 30050 ) < 1 then 
say_title ( gameforge . collect_quest_lv60 . _50_sayTitle ) 
say ( gameforge . collect_quest_lv60 . _205_say ) 
return 
end 
say_title ( gameforge . collect_quest_lv60 . _50_sayTitle ) 
say ( gameforge . collect_quest_lv60 . _170_say ) 
pc . remove_item ( 30050 , 1 ) 
wait ( ) 
local if_fail_show_wait_info = not collect_data . is_no_time_on_fail ( ) 
if collect_data . take_chance ( 60 ) then 
if pc . getqf ( "collect_count" ) < 19 then 
local index = pc . getqf ( "collect_count" ) + 1 
pc . setqf ( "collect_count" , index ) 
say_title ( gameforge . collect_quest_lv60 . _140_sayTitle ) 
say ( string . format ( gameforge . collect_quest_lv60 . _180_say , 20 - pc . getqf ( "collect_count" ) ) ) 
return 
end 
say_title ( gameforge . collect_quest_lv60 . _50_sayTitle ) 
say ( gameforge . collect_quest_lv60 . _190_say ) 
pc . setqf ( "collect_count" , 0 ) 
collect_data . reset_time ( ) 
set_state ( "key_item" ) 
return 
else 
say_title ( gameforge . collect_quest_lv60 . _50_sayTitle ) 
say ( gameforge . collect_quest_lv60 . _200_say ) 
say ( ) 
if if_fail_show_wait_info then 
say ( gameforge . collect_quest_lv60 . fail_wait_info ) 
end 
return 
end 
