say_title ( gameforge . collect_herb_lv10 . _150_sayTitle ) 
say ( gameforge . collect_herb_lv15 . _110_say ) 
pc . remove_item ( 50702 , 1 ) 
wait ( ) 
local pass_percent = 90 
local s = number ( 1 , 100 ) 
if s <= pass_percent then 
if pc . getqf ( "collect_count" ) < 4 then 
local index = pc . getqf ( "collect_count" ) + 1 
pc . setqf ( "collect_count" , index ) 
say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( string . format ( gameforge . collect_herb_lv7 . _90_say , 5 - pc . getqf ( "collect_count" ) ) ) 
return 
end 
say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( gameforge . collect_herb_lv7 . _95_say ) 
say_title ( gameforge . buy_fishrod . _210_sayTitle ) 
say_reward ( gameforge . collect_herb_lv7 . _100_sayReward ) 
pc . setqf ( "collect_count" , 0 ) 
clear_letter ( ) 
set_state ( "__complete" ) 
give_reward ( "herb_lv7" ) 
return 
else 
say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( gameforge . collect_herb_lv7 . _150_say ) 
return 
end 
