say_title ( gameforge . collect_herb_lv10 . _150_sayTitle ) 
say ( gameforge . collect_herb_lv10 . _160_say ) 
pc . remove_item ( 50703 , 1 ) 
wait ( ) 
local pass_percent = 90 
local s = number ( 1 , 100 ) 
if s <= pass_percent then 
if pc . getqf ( "collect_count" ) < 4 then 
local index = pc . getqf ( "collect_count" ) + 1 
pc . setqf ( "collect_count" , index ) 
say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( string . format ( gameforge . collect_herb_lv10 . _170_say , 5 - pc . getqf ( "collect_count" ) ) ) 
return 
end 
say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( gameforge . collect_herb_lv10 . _180_say ) 
wait ( ) 
say ( gameforge . collect_herb_lv10 . _190_say ) 
say_reward ( gameforge . collect_herb_lv10 . _200_sayReward ) 
pc . setqf ( "collect_count" , 0 ) 
clear_letter ( ) 
set_state ( "__complete" ) 
give_reward ( "herb_lv10" ) 
return 
else 
say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( gameforge . collect_herb_lv10 . _210_say ) 
return 
end 
