say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( gameforge . collect_herb_lv25 . _90_say ) 
pc . remove_item ( 50706 , 1 ) 
wait ( ) 
local pass_percent = 70 
local s = number ( 1 , 100 ) 
if s <= pass_percent then 
if pc . getqf ( "collect_count" ) < 9 then 
local index = pc . getqf ( "collect_count" ) + 1 
pc . setqf ( "collect_count" , index ) 
say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( string . format ( gameforge . collect_herb_lv25 . _100_say , 10 - pc . getqf ( "collect_count" ) ) ) 
return 
end 
say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( gameforge . collect_herb_lv25 . _110_say ) 
say_reward ( gameforge . collect_herb_lv25 . _120_sayReward ) 
pc . setqf ( "collect_count" , 0 ) 
clear_letter ( ) 
set_state ( "__complete" ) 
give_reward ( "herb_lv25" ) 
return 
else 
say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( gameforge . collect_herb_lv25 . _170_say ) 
return 
end 
