say_title ( gameforge . collect_herb_lv10 . _150_sayTitle ) 
say ( gameforge . collect_herb_lv10 . _160_say ) 
pc . remove_item ( 50701 , 1 ) 
wait ( ) 
local pass_percent = 90 
local s = number ( 1 , 100 ) 
if s <= pass_percent then 
if pc . getqf ( "collect_count" ) < 4 then 
local index = pc . getqf ( "collect_count" ) + 1 
pc . setqf ( "collect_count" , index ) 
say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( string . format ( gameforge . collect_herb_lv4 . _110_say , 5 - pc . getqf ( "collect_count" ) ) ) 
return 
end 
say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( gameforge . collect_herb_lv4 . _120_say ) 
say_title ( gameforge . collect_herb_lv4 . _130_sayTitle ) 
say_reward ( gameforge . collect_herb_lv4 . _140_sayReward ) 
set_state ( "__complete" ) 
local weapon_reward_by_job = { 
[ JOB_SHAMAN ] = { 7003 } , 
[ JOB_ASSASSIN ] = { 1003 , 2003 } , 
[ JOB_WARRIOR ] = { 13 , 3003 } , 
[ JOB_SURA ] = { 13 } 
} 
give_reward ( "herb_lv4" ) 
select_weapon_reward ( weapon_reward_by_job [ pc . job ] ) 
pc . setqf ( "collect_count" , 0 ) 
clear_letter ( ) 
else 
say_title ( gameforge . collect_herb_lv10 . _50_sayTitle ) 
say ( gameforge . collect_herb_lv4 . _170_say ) 
return 
end 
