target . delete ( "__TARGET4__" ) 
say_title ( gameforge . new_quest_lv29 . _082_say_title ) 
say ( gameforge . new_quest_lv29 . _052_say ) 
wait ( ) 
say_title ( gameforge . new_quest_lv29 . _082_say_title ) 
say ( gameforge . new_quest_lv29 . _053_say ) 
local hayCount = pc . count_item ( 50054 ) 
if hayCount < 6 then 
new_quest_lv29_neededAmountDrop = 6 
q . done ( ) 
set_state ( "cutting_hay" ) 
else 
say ( gameforge . new_quest_lv29 . _065_1_say ) 
q . done ( ) 
set_state ( "calming_yonah" ) 
end 
