say_title ( gameforge . horse_exchange_ticket . _20_sayTitle ) 
say ( gameforge . subquest_36 . _150_say ) 
local s = select ( gameforge . subquest_36 . _190_select , gameforge . subquest_31 . _180_select ) 
if 1 == s then 
say_pc_name ( ) 
say ( gameforge . subquest_36 . _160_say ) 
return 
else 
say_pc_name ( ) 
say ( gameforge . subquest_36 . _170_say ) 
wait ( ) 
say_title ( gameforge . horse_exchange_ticket . _20_sayTitle ) 
say ( gameforge . subquest_36 . _180_say ) 
local s = select ( gameforge . subquest_36 . _190_select , gameforge . subquest_31 . _180_select ) 
if 1 == s then 
say_pc_name ( ) 
say ( gameforge . subquest_36 . _200_say ) 
return 
elseif 2 == s then 
say_pc_name ( ) 
say ( gameforge . subquest_36 . _210_say ) 
set_state ( "__GIVEUP__" ) 
end 
end 
