if get_time ( ) < pc . getqf ( "limit_time" ) then 
say_title ( gameforge . subquest_08 . _240_sayTitle ) 
say ( gameforge . subquest_24 . _180_say ) 
local s = select ( gameforge . subquest_24 . _190_select , gameforge . subquest_24 . _200_select ) 
if 2 == s then 
say_title ( gameforge . subquest_08 . _240_sayTitle ) 
say ( gameforge . subquest_24 . _210_say ) 
local s = select ( gameforge . subquest_24 . _220_select , gameforge . subquest_24 . _230_select ) 
if 2 == s then 
say_title ( gameforge . subquest_08 . _240_sayTitle ) 
say ( gameforge . subquest_24 . _240_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . subquest_08 . _240_sayTitle ) 
say ( gameforge . subquest_24 . _250_say ) 
return 
end 
say_title ( gameforge . subquest_08 . _240_sayTitle ) 
say ( gameforge . subquest_24 . _260_say ) 
return 
end 
say_title ( gameforge . subquest_08 . _240_sayTitle ) 
say ( gameforge . subquest_24 . _270_say ) 
set_state ( "__FAIL__" ) 
