target . delete ( "__TARGET__" ) 
say_title ( gameforge . cube . _40_sayTitle ) 
say ( gameforge . subquest_25 . _180_say ) 
wait ( ) 
say_title ( gameforge . cube . _40_sayTitle ) 
say ( gameforge . subquest_25 . _190_say ) 
local s = select ( gameforge . subquest_01 . _50_select , gameforge . subquest_25 . _200_select ) 
if 2 == s then 
say ( gameforge . subquest_25 . _210_say ) 
local a = select ( gameforge . subquest_12 . _select_yes , gameforge . subquest_12 . _select_no ) 
if 2 == a then 
say_title ( gameforge . cube . _40_sayTitle ) 
say ( gameforge . subquest_25 . _220_say ) 
return 
end 
say_title ( gameforge . cube . _40_sayTitle ) 
say ( gameforge . subquest_25 . _230_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . cube . _40_sayTitle ) 
say ( gameforge . subquest_25 . _240_say ) 
set_state ( "find_flower" ) 
