target . delete ( "__TARGET5__" ) 
say_title ( gameforge . new_quest_lv42 . _034_say_title ) 
if pc . count_item ( 30175 ) >= 2 then 
pc . remove_item ( 30175 , 2 ) 
say ( gameforge . new_quest_lv42 . _080_say ) 
pc . setqf ( "reward_given" , 1 ) 
say_title ( gameforge . new_quest_lv43 . _052_say_title ) 
set_state ( "__COMPLETE__" ) 
give_reward ( "new_quest_lv43" ) 
q . done ( ) 
return 
else 
say ( gameforge . new_quest_lv42 . _083_say ) 
say_reward ( gameforge . new_quest_lv42 . _084_say_reward ) 
q . done ( ) 
set_state ( "goto_smith" ) 
end 
