target . delete ( "__TARGET5__" ) 
say_title ( gameforge . new_quest_lv28 . _038_say_title ) 
if pc . count_item ( new_quest_lv28_drop1 ) >= 1 then 
say ( gameforge . new_quest_lv28 . _042_say ) 
say ( gameforge . new_quest_lv28 . _043_say ) 
pc . remove_item ( new_quest_lv28_drop1 , pc . count_item ( new_quest_lv28_drop1 ) ) 
set_state ( "back_to_ahyu" ) 
return 
else 
say ( gameforge . new_quest_lv28 . _044_say ) 
say ( gameforge . new_quest_lv28 . _045_say_reward ) 
set_state ( "hunting" ) 
end 
