target . delete ( "__TARGET__" ) 
if pc . count_item ( "30136" ) >= 1 then 
say_title ( gameforge . main_quest_lv32 . _510_sayTitle ) 
say ( gameforge . subquest_38 . _140_say ) 
pc . remove_item ( "30136" , 1 ) 
set_state ( "COMPLETE" ) 
give_reward ( "subquest_38" ) 
clear_letter ( ) 
return 
else 
say_title ( gameforge . main_quest_lv32 . _510_sayTitle ) 
say ( gameforge . subquest_38 . _180_say ) 
local s = select ( gameforge . subquest_38 . _190_select , gameforge . subquest_24 . _200_select ) 
if 2 == s then 
say ( gameforge . subquest_37 . _50_say ) 
local a = select ( gameforge . subquest_12 . _select_yes , gameforge . subquest_12 . _select_no ) 
if 1 == a then 
say_title ( gameforge . main_quest_lv32 . _510_sayTitle ) 
say ( gameforge . subquest_38 . _200_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . main_quest_lv32 . _510_sayTitle ) 
say ( gameforge . subquest_38 . _210_say ) 
end 
end 
