target . delete ( "__TARGET__" ) 
say_title ( gameforge . main_quest_lv3 . _160_sayTitle ) 
say ( gameforge . subquest_06 . _30_say ) 
local s = select ( gameforge . subquest_06 . _40_select , gameforge . subquest_06 . _50_select ) 
if 2 == s then 
say ( gameforge . subquest_06 . _60_say ) 
local a = select ( gameforge . subquest_06 . _70_select , gameforge . subquest_06 . _80_select ) 
if 2 == a then 
say_title ( gameforge . main_quest_lv3 . _160_sayTitle ) 
say ( gameforge . subquest_06 . _90_say ) 
return 
end 
say_title ( gameforge . main_quest_lv3 . _160_sayTitle ) 
say ( gameforge . subquest_06 . _100_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . main_quest_lv3 . _160_sayTitle ) 
say ( gameforge . subquest_06 . _110_say ) 
set_state ( "ask_blacksmith" ) 
