target . delete ( "__TARGET6__" ) 
say_title ( gameforge . new_quest_lv7 . _012_say_title ) 
if ( pc . count_item ( 30169 ) < 1 or pc . count_item ( 30170 ) < 1 or pc . count_item ( 30171 ) < 1 ) then 
say ( gameforge . new_quest_lv7 . _110_say ) 
say_reward ( string . format ( gameforge . new_quest_lv7 . _085_say_reward , 1 - pc . count_item ( 30169 ) ) ) 
say_reward ( string . format ( gameforge . new_quest_lv7 . _086_say_reward , 1 - pc . count_item ( 30170 ) ) ) 
say_reward ( string . format ( gameforge . new_quest_lv7 . _087_say_reward , 1 - pc . count_item ( 30171 ) ) ) 
say ( gameforge . new_quest_lv7 . _081_say ) 
set_state ( "collect_flowers" ) 
else 
pc . remove_item ( 30169 , 1 ) 
pc . remove_item ( 30170 , 1 ) 
pc . remove_item ( 30171 , 1 ) 
pc . give_item2 ( 30172 ) 
say ( gameforge . new_quest_lv7 . _115_say ) 
if pc . get_empire ( ) == 1 then 
say_reward ( gameforge . new_quest_lv7 . _118_say_reward ) 
end 
if pc . get_empire ( ) == 2 then 
say_reward ( gameforge . new_quest_lv7 . _116_say_reward ) 
end 
if pc . get_empire ( ) == 3 then 
say_reward ( gameforge . new_quest_lv7 . _117_say_reward ) 
end 
q . done ( ) 
set_state ( "find_empire" ) 
return 
end 
