target . delete ( "__TARGET2_" ) 
say_title ( gameforge . buy_fishrod . _210_sayTitle ) 
say ( gameforge . subquest_18 . _140_say ) 
wait ( ) 
say_title ( gameforge . subquest_05 . _30_sayTitle ) 
say ( gameforge . subquest_18 . _150_say ) 
local s = select ( 
gameforge . subquest_18 . _153_select , 
gameforge . subquest_18 . _157_select ) 
if 1 == s then 
say_title ( gameforge . subquest_05 . _30_sayTitle ) 
say ( gameforge . subquest_18 . _160_say ) 
set_state ( "report_true" ) 
elseif 2 == s then 
say_title ( gameforge . subquest_05 . _30_sayTitle ) 
say ( gameforge . subquest_18 . _170_say ) 
set_state ( "report_false" ) 
end 
