target . delete ( "__TARGET__" ) 
say_title ( gameforge . subquest_05 . _30_sayTitle ) 
say ( gameforge . subquest_45 . _20_say ) 
wait ( ) 
say_title ( gameforge . subquest_05 . _30_sayTitle ) 
say ( gameforge . subquest_45 . _30_say ) 
local s = select ( gameforge . subquest_45 . _40_select ) 
if 2 == s then 
say ( gameforge . subquest_45 . _50_say ) 
local a = select ( gameforge . subquest_12 . _select_yes , gameforge . subquest_12 . _select_no ) 
if 2 == a then 
say_title ( gameforge . subquest_05 . _30_sayTitle ) 
say ( gameforge . subquest_45 . _60_say ) 
return 
end 
say_title ( gameforge . subquest_05 . _30_sayTitle ) 
say ( gameforge . subquest_45 . _70_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . subquest_05 . _30_sayTitle ) 
say ( gameforge . subquest_45 . _80_say ) 
set_state ( "WHAT_IS_MILGYO" ) 
