npc_name ( ) 
local player_map = pc . get_map_index ( ) 
local is_in_any_city = is_player_in_any_m1 ( ) or is_player_in_any_m2 ( ) 
if is_in_any_city then 
say_split ( translate . map_warp . talk1 ) 
else 
say_split ( translate . map_warp . talk1_outside ) 
end 
wait ( ) 
local player_level = pc . get_level ( ) 
local base_price = math . max ( math . floor ( player_level / 5 ) * 1000 , 1000 ) 
if pc . get_map_index ( ) >= 181 and pc . get_map_index ( ) <= 183 then 
base_price = 0 
elseif not is_in_any_city then 
base_price = base_price * 1.5 
end 
if not map_warp . check ( base_price , player_level ) then 
return 
end 
local page_count = 1 
if is_in_any_city and pc . get_level ( ) >= 60 then 
page_count = 2 
end 
local map_index , price = map_warp . process_teleport_list ( 1 , page_count , base_price ) 
if map_index > 0 then 
npc_name ( ) 
if is_in_any_city then 
say_split ( translate . map_warp . info_tp_from_city ) 
else 
say_split ( translate . map_warp . info_tp_outside_city ) 
end 
wait ( ) 
if not map_warp . check ( price , player_level ) then 
return 
end 
pc . change_money ( - price ) 
debug ( "warp na %d" , map_index ) 
if map_index == 66 then 
pc . warp ( 5900 * 100 , 1114 * 100 ) 
else 
pc . teleport ( map_index ) 
end 
return 
end 
setskin ( NOWINDOW ) 
