target . delete ( "__TARGET4__" ) 
say_title ( gameforge . new_quest_lv22 . _019_say_title ) 
q . done ( ) 
if pc . count_item ( 35002 ) >= 1 and get_time ( ) - pc . getqf ( "new_quest_lv22_startTime" ) <= 1200 then 
pc . remove_item ( 35002 , 1 ) 
say ( gameforge . new_quest_lv22 . _085_say ) 
say ( gameforge . new_quest_lv22 . _086_say ) 
say ( gameforge . new_quest_lv22 . _087_say ) 
set_state ( "__COMPLETE__" ) 
give_reward ( "new_quest_lv22_success" ) 
return 
elseif pc . count_item ( 35002 ) >= 1 and get_time ( ) - pc . getqf ( "new_quest_lv22_startTime" ) > 1200 then 
pc . remove_item ( 35002 , 1 ) 
say ( gameforge . new_quest_lv22 . _085_say ) 
say ( gameforge . new_quest_lv22 . _089_say ) 
wait ( ) 
say_title ( gameforge . new_quest_lv22 . _019_say_title ) 
say ( gameforge . new_quest_lv22 . _090_say ) 
set_state ( "__COMPLETE__" ) 
give_reward ( "new_quest_lv22_fail" ) 
return 
else 
say ( gameforge . new_quest_lv22 . _091_say ) 
set_state ( "hunting" ) 
end 
