target . delete ( "__TARGET__" ) 
local empire = pc . get_empire ( ) 
say_title ( gameforge . new_quest_lv7 . _011_say_title ) 
say ( gameforge . new_quest_lv7 . _021_say ) 
if empire == 1 then 
say ( gameforge . new_quest_lv7 . _022_say ) 
end 
if empire == 2 then 
say ( gameforge . new_quest_lv7 . _023_say ) 
end 
if empire == 3 then 
say ( gameforge . new_quest_lv7 . _024_say ) 
end 
wait ( ) 
say_title ( gameforge . new_quest_lv7 . _011_say_title ) 
say ( gameforge . new_quest_lv7 . _030_say ) 
say ( gameforge . new_quest_lv7 . _031_say ) 
local doquest = select ( gameforge . subquest_06 . _40_select , gameforge . subquest_12 . _50_select , gameforge . new_quest_lv75 . _290_2_select ) 
if doquest == 1 then 
set_state ( "ask_oldwoman" ) 
elseif doquest == 3 then 
say ( gameforge . subquest_06 . _60_say ) 
local abortquest = select ( gameforge . subquest_06 . _70_select , gameforge . subquest_06 . _80_select ) 
if abortquest == 1 then 
set_state ( "__GIVEUP__" ) 
else 
say_title ( gameforge . new_quest_lv7 . _011_say_title ) 
say ( gameforge . subquest_11 . _80_say ) 
return 
end 
else 
say_title ( gameforge . new_quest_lv7 . _011_say_title ) 
say ( gameforge . subquest_11 . _80_say ) 
return 
end 
