target . delete ( "__TARGET__" ) 
say_title ( gameforge . new_quest_lv42 . _022_say_title ) 
say ( gameforge . new_quest_lv42 . _023_say ) 
say ( gameforge . new_quest_lv42 . _024_say ) 
local doquest = select ( gameforge . new_quest_lv42 . _026_select , gameforge . subquest_12 . _50_select , gameforge . new_quest_lv75 . _290_2_select ) 
if doquest == 1 then 
q . done ( ) 
set_state ( "ask_fisher" ) 
elseif doquest == 3 then 
say ( gameforge . subquest_06 . _60_say ) 
local abortquest = select ( gameforge . subquest_06 . _70_select , gameforge . subquest_06 . _80_select ) 
if abortquest == 1 then 
set_state ( "__GIVEUP__" ) 
else 
say_title ( gameforge . new_quest_lv42 . _022_say_title ) 
say ( gameforge . subquest_11 . _80_say ) 
return 
end 
else 
say_title ( gameforge . new_quest_lv42 . _022_say_title ) 
say ( gameforge . subquest_11 . _80_say ) 
return 
end 
