target . delete ( "__TARGET__" ) 
if pc . count_item ( "30146" ) >= 50 then 
say_title ( gameforge . subquest_06 . _320_sayTitle ) 
say ( gameforge . subquest_49 . _300_say ) 
say_item_vnum ( 30149 ) 
pc . give_item2 ( 30149 ) 
set_state ( "back_to_boy" ) 
pc . remove_item ( 30146 , 50 ) 
return 
else 
say ( gameforge . subquest_49 . _310_say ) 
local s = select ( gameforge . subquest_49 . _320_select , gameforge . find_brother_article . _170_select ) 
if 2 == s then 
say_title ( gameforge . subquest_06 . _320_sayTitle ) 
say ( gameforge . subquest_49 . _330_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . subquest_06 . _320_sayTitle ) 
say ( gameforge . subquest_49 . _340_say ) 
end 
