say_title ( gameforge . check_trans_ticket . _15_sayTitle ) 
if not pc . can_warp ( ) then 
say_split ( translate . general . wait_after_exchange ) 
say ( ) 
return 
end 
say ( gameforge . check_trans_ticket . _20_say ) 
wait ( ) 
local isPremium = pc . is_premium_subscription ( ) 
local hasTicket = pc . count_item ( 71095 ) + pc . count_item ( 71130 ) > 0 
local minLevelToEnter = 15 
local minLevelToEnterPremium = 15 
if pc . get_level ( ) < minLevelToEnter then 
npc_name ( ) 
say_reward ( msg ( translate . general . low_lvl , minLevelToEnter ) ) 
say ( ) 
return 
elseif isPremium and not hasTicket and pc . get_level ( ) < minLevelToEnterPremium then 
npc_name ( ) 
say_split ( msg ( translate . check_trans_ticket . low_lvl_premium , minLevelToEnterPremium ) , say_reward ) 
say ( ) 
return 
end 
isPremium = isPremium and pc . get_level ( ) >= minLevelToEnterPremium 
if isPremium or hasTicket then 
say_title ( gameforge . check_trans_ticket . _15_sayTitle ) 
say ( gameforge . check_trans_ticket . _30_say ) 
wait ( ) 
if false == pc . can_warp ( ) then 
say ( gameforge . check_trans_ticket . _160_say ) 
return 
end 
if isPremium or hasTicket then 
if not isPremium and pc . count_item ( 71130 ) >= 1 then 
pc . remove_item ( 71130 , 1 ) 
elseif not isPremium and pc . count_item ( 71095 ) >= 1 then 
pc . remove_item ( 71095 , 1 ) 
else 
if not isPremium then 
debug ( "cheat?" ) 
return 
end 
end 
pc . warp ( 704100 , 464100 ) 
else 
return 
end 
else 
say_title ( gameforge . check_trans_ticket . _15_sayTitle ) 
say ( gameforge . check_trans_ticket . _40_say ) 
wait ( ) 
end 
