target . delete ( "__TARGET__" ) 
say_title ( gameforge . find_squareguard . _130_sayTitle ) 
say ( gameforge . subquest_01 . _30_say ) 
say_item_vnum ( 30130 ) 
say ( gameforge . subquest_01 . _40_say ) 
local s = select ( gameforge . subquest_01 . _50_select , gameforge . subquest_01 . _60_select ) 
if 2 == s then 
say ( gameforge . subquest_01 . _70_say ) 
local a = select ( gameforge . subquest_12 . _select_yes , gameforge . subquest_12 . _select_no ) 
if 2 == a then 
say_title ( gameforge . find_squareguard . _130_sayTitle ) 
say ( gameforge . subquest_01 . _80_say ) 
return 
end 
say_title ( gameforge . find_squareguard . _130_sayTitle ) 
say ( gameforge . subquest_01 . _90_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . subquest_01 . _100_sayTitle ) 
say ( gameforge . subquest_01 . _110_say ) 
set_state ( "to_yeonnahwan" ) 
