local price = 1e+07 
say_npc ( ) 
say ( msg ( gameforge . guild_building_melt . _130_say , parse_number ( price ) ) ) 
wait ( ) 
if pc . get_gold ( ) < price then 
say ( msg ( gameforge . guild_building_melt . _140_say , parse_number ( price ) ) ) 
else 
local sel = 0 
local timetable1 = { gameforge . guild_building_melt . _180_say , 
gameforge . guild_building_melt . _190_say , 
gameforge . guild_building_melt . _200_say , 
gameforge . guild_building_melt . _210_say , 
gameforge . guild_building_melt . _220_say , 
gameforge . locale . levelup . prev_quest_go , 
gameforge . guild_building_melt . _170_say } 
local valuetable1 = { 14043 , 14045 , 14046 , 14047 , 14048 , 1 , 3 } 
local timetable2 = { gameforge . guild_building_melt . _230_say , 
gameforge . guild_building_melt . _240_say , 
gameforge . guild_building_melt . _250_say , 
gameforge . guild_building_melt . _260_say , 
gameforge . locale . levelup . prev_quest_go , 
gameforge . map_warp . _96_select , 
gameforge . guild_building_melt . _170_say } 
local valuetable2 = { 14049 , 14050 , 10451 , 14052 , 2 , 0 , 3 } 
local timetable3 = { gameforge . guild_building_melt . _270_say , 
gameforge . guild_building_melt . _280_say , 
gameforge . guild_building_melt . _290_say , 
gameforge . map_warp . _96_select , 
gameforge . guild_building_melt . _170_say } 
local valuetable3 = { 14053 , 14054 , 14055 , 1 , 3 } 
repeat 
say_npc ( ) 
say ( gameforge . guild_building_melt . _150_say ) 
if sel == 0 then 
local s = select_table ( timetable1 ) 
sel = valuetable1 [ s ] 
elseif sel == 1 then 
local s = select_table ( timetable2 ) 
sel = valuetable2 [ s ] 
elseif sel == 2 then 
local s = select_table ( timetable3 ) 
sel = valuetable3 [ s ] 
end 
until sel > 2 
if sel ~= 3 then 
npc_num = sel + 20060 - 14043 
if npc_num == npc . get_race ( ) then 
say ( gameforge . guild_building_melt . _160_say ) 
else 
pc . changegold ( - price ) 
building . reconstruct ( sel ) 
end 
end 
end 
