if pc . count_item ( new_quest_lv29_drop ) < new_quest_lv29_neededAmountDrop and pc . getqf ( "hayFromTaurean" ) == 1 and pc . getqf ( "hayIndex" ) > 0 then 
say_pc_name ( ) 
say_reward ( gameforge . new_quest_lv29 . _071_say_reward ) 
wait ( ) 
say_title ( gameforge . new_quest_lv29 . _033_say_title ) 
say ( gameforge . new_quest_lv29 . _072_say_reward ) 
pc . setqf ( "hayFromTaurean" , 0 ) 
pc . give_item2 ( new_quest_lv29_drop ) 
local qfindex = pc . getqf ( "hayIndex" ) - 1 
pc . setqf ( "hayIndex" , qfindex ) 
notice_multiline ( string . format ( gameforge . new_quest_lv29 . _073_notice , new_quest_lv29_neededAmountDrop - pc . count_item ( new_quest_lv29_drop ) ) , notice ) 
if new_quest_lv29_neededAmountDrop <= pc . count_item ( new_quest_lv29_drop ) or pc . getqf ( "hayIndex" ) == 0 then 
q . done ( ) 
set_state ( "calming_yonah" ) 
end 
else 
say_title ( gameforge . new_quest_lv29 . _033_say_title ) 
say ( gameforge . new_quest_lv29 . _074_say_reward ) 
end 
