target . delete ( "__TARGET__" ) 
say_title ( gameforge . subquest_49 . _30_sayTitle ) 
say ( gameforge . subquest_49 . _40_say ) 
wait ( ) 
say_title ( gameforge . subquest_49 . _30_sayTitle ) 
say ( gameforge . subquest_49 . _50_say ) 
local s = select ( gameforge . subquest_46 . _50_select , gameforge . subquest_46 . _60_select ) 
if 2 == s then 
say_title ( gameforge . subquest_49 . _30_sayTitle ) 
say ( gameforge . subquest_49 . _60_say ) 
local a = select ( gameforge . subquest_12 . _select_yes , gameforge . subquest_12 . _select_no ) 
if 2 == a then 
say_title ( gameforge . npc_talk . _680_sayTitle ) 
say ( gameforge . subquest_49 . _70_say ) 
return 
end 
say_title ( gameforge . subquest_49 . _30_sayTitle ) 
say ( gameforge . subquest_49 . _80_say ) 
set_state ( "__GIVEUP__" ) 
return 
end 
say_title ( gameforge . subquest_49 . _30_sayTitle ) 
say ( gameforge . subquest_49 . _90_say ) 
set_state ( "ask_to_youhwarang" ) 
